# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 06:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2017, 2, 4)),
        ),
    ]
